### PR TITLE
Fix for Xcode 15 build error

### PR DESCRIPTION
**Pull request by Ariandr**
Hi @mrackwitz 
I implemented the fix for Xcode 15 build error.
Since it's not just a warning, but an error that prevents the project from building, I think it's important.
Thanks

### CODE REVIEW

**Review by jrdaher — APPROVED** [review]

**Comment by jrdaher** [comment]
Could we please merge this @mrackwitz 🙏

**Comment by jrdaher** [comment]
temporary fix:

Script in project folder
```
import fileinput
import sys

def replaceAll(file, searchExp, replaceExp):
    for line in fileinput.input(file, inplace=1):
        if searchExp in line:
            line = line.replace(searchExp,replaceExp)
        sys.stdout.write(line)

rationale_for_script = """
       //This script exists until https://github.com/mrackwitz/MRProgress/pull/142/files is merged
       //It exists to fix a build issue in Xcode 15
"""

file_to_patch = "./Pods/MRProgress/src/Components/MRProgressOverlayView.m"

text_to_find = "[((id)self.modeView) setProgress:self.progress];"

text_to_replace_match = rationale_for_script + "       [self.modeView performSelector:@selector(setProgress:) withObject:[NSNumber numberWithFloat:self.progress]];"


replaceAll(file_to_patch, text_to_find, text_to_replace_match)
```


in Podfile
```
post_install do |installer|
  system("python3 UpdateMPProgressPodForXcode15.py")
end
```

**Comment by jrdaher** [comment]
@Ariandr ☝️

**Comment by Ariandr** [comment]
Thanks @jrdaher

**Comment by anum-ijaz-confiz** [comment]
The mentioned fix worked for me as well since it was a blocker in building the project with Xcode 15. **@mrackwitz** kindly merge the changes.

**Review by hafiz-mohsin-confiz — APPROVED** [review]
Looks good.

**Comment by mrackwitz** [comment]
Hey folks, thanks for the PR. Looks good to me.

I'm sorry that I haven't responded here much sooner.
@jrdaher Particularly sorry given the awful workaround you had to find in the meantime, but thanks for sharing.

**Comment by hafiz-mohsin-confiz** [comment]
@mrackwitz 
Kindly provide the new library update with the fix on CocoaPods so that we will update it.
Thanks

**Comment by Ariandr** [comment]
Hi @mrackwitz 
Do you have a chance to update the CocoaPods version to have this PR included?

**Pull request merged**
